### ISSUE TITLE
Error in 'Alignment' module with MAFFT alignment

### ISSUE THREAD

**Issue by IdoBar** [AliTVTeam/AliTV-perl-interface#136]
Hi,

I read your recent publication and I'm really interested in trying out AliTV, but I can't get it to work with my data.
I got 8 viral genomes in FASTA format which were aligned by MAFFT.
I added the following lines to the yaml file:
```
---
alignment:
    program: importer
    parameter:
        - "../WSSV_genomes_MAFFT_alignment.fasta"

genomes:
  - name: AF332093.3
    sequence_files:
      - WSSV_genome_AF332093.3.fasta
  - name: AF369029.2
    sequence_files:
      - WSSV_genome_AF369029.2.fasta
  - name: AF440570.1
    sequence_files:
      - WSSV_genome_AF440570.1.fasta
  - name: JX515788.1
    sequence_files:
      - WSSV_genome_JX515788.1.fasta
  - name: KR083866.1
    sequence_files:
      - WSSV_genome_KR083866.1.fasta
  - name: KT995470.1
    sequence_files:
      - WSSV_genome_KT995470.1.fasta
  - name: KT995471.1
    sequence_files:
      - WSSV_genome_KT995471.1.fasta
  - name: KT995472.1
    sequence_files:
      - WSSV_genome_KT995472.1.fasta
  - name: KU216744.1
    sequence_files:
      - WSSV_genome_KU216744.1.fasta
output:
  conf: conf.json
  data: data.json
  filter: filter.json
```
And ran it with the following command:
`perl -Ilib ~/etc/tools/Annotation/AliTV-perl-interface-1.0.2/bin/alitv.pl --overwrite --project WSSV WSSV.yml
`
However, I get the following error:
```
Use of uninitialized value in subroutine entry at /home/ibar/etc/tools/Annotation/AliTV-perl-interface-1.0.2/bin/../lib/AliTV/Alignment.pm line 262, <GEN9> line 55170.
FATAL - unable to create features at /home/ibar/etc/tools/Annotation/AliTV-perl-interface-1.0.2/bin/../lib/AliTV/Alignment.pm line 305
```
When I tried to use `lastz` to align the sequences (giving the fasta files as input, without a yaml file), it produced a different error:
`FATAL - Unable to load alignment module 'AliTV::Alignment::lastz' at /home/ibar/etc/tools/Annotation/AliTV-perl-interface-1.0.2/bin/alitv.pl line 117.`

Thank you, Ido
