### ISSUE TITLE
unable to identify sequence in sequence set by name

### ISSUE THREAD

**Issue by 0xaf1f** [AliTVTeam/AliTV-perl-interface#167]
I'm trying to run `alitv.pl` with an existing maf alignment file and I'm getting an error about a sequence that isn't found that is definitely there.

```
INFO - MAF input file and buggy BioPerl detected... Therefore, workaround for revcom issue activated
FATAL - Unable to identify sequence in sequence set by name '4_0010' at /path/to/utils/AliTV-perl-interface/bin/../lib/AliTV.pm line 99.

Unable to identify sequence in sequence set by name '4_0010' at /path/to/utils/AliTV-perl-interface/bin/../lib/AliTV.pm line 99.
```

Also, I replaced all occurrences of the hyphen in the original sequence name (4-0010) with an underscore, but it'd be nice to not have to do that.

**Comment by iimog** [comment]
Hmm, I can't tell what's going wrong there. Can you provide a minimal example of a maf file and the exact call to `alitv.pl` so I can reproduce and debug it?

I agree that it would be more convenient if manually replacing characters in IDs would not be necessary. Maybe @greatfireball has an idea how to fix that?

**Comment by 0xaf1f** [comment]
Well, so I'm running using a single maf file representing a multiple sequence alignment for about 100 samples. Each sample has a tsv feature file. I was looking into your test data directory to see if I could modify one of your existing test cases to look like mine, but I didn't find a maf file and tsv feature file that could be used together.

My yaml file looks like

```
genomes:
    -
         name: 1_0021
         sequence_files:
              - renamed-seqs/1_0021.fasta
          feature_files:
              blocks:
                  - 500/features.tsv

...
...

alignment:
    program: importer
    parameter:
        - "alignment.manglednames.maf"
```

where each fasta file has a single sequence and whose name matches what I put in the name field, so the header of `renamed_seqs/1_0021.fasta` is `>1_0021`

There is nothing special about my command-line invocation. I am just using `/path/to/AliTV-perl-interface/bin/alitv.pl --project tb --overwrite alitv.yaml`
