### ISSUE TITLE
Demo annotation occurred in my own json file.

### ISSUE THREAD

**Issue by wh960823** [AliTVTeam/AliTV-perl-interface#171]
Hi, I am interested in your work on genome comparison visulization. However, when I creat my own json file using my own data and annotation tsv. file, the ndh, invert repeat annoatations in demo occurred instead of my annotations. Could you please guide me to solve this problem ?
Sincerely,
Hao

**Comment by iimog** [comment]
Hi Hao,
I think this is related to https://github.com/AliTVTeam/AliTV/issues/123. My guess is, that your json is just fine, containing none of the demo features and only the annotation you provided. The problem is, that the web interface does not by default change the visibility of features when you load a new json file. You should be able to click on "Show/Hide Annotations" (see screenshot below) to hide the annotations you don't need and select a style for the annotations you want to show.
If there is really an issue with the json file, it would be awesome if you could share the command you used for creation and the output json for inspection.

**Comment by iimog** [comment]
![image](https://user-images.githubusercontent.com/7403236/178104064-190b477e-111f-4d6b-861d-109a2e13c592.png)

**Comment by wh960823** [comment]
Thanks for your reply! I tried to show annotations in the web interface, but no list of my annotations in the list. Please see the yaml file attached below. 

command: `alitv.pl --project test /home/bioinfo/Crabs/hcl/test_AliTV/a.yaml --overwrite`

a.yaml
```
genomes: 
   -
    name: Bradyrhizobium_canariense_WSM471
    sequence_files:
      - /home/bioinfo/Crabs/hcl/test_AliTV/Bradyrhizobium_canariense_WSM471.fasta
    feature_files:
      nif: 
             - /home/bioinfo/Crabs/hcl/test_AliTV/nif.tsv           
   - 
    name: Bradyrhizobium_daqingense_CCBAU15774
    sequence_files:
      - /home/bioinfo/Crabs/hcl/test_AliTV/Bradyrhizobium_daqingense_CCBAU15774.fasta
    feature_files:
      nif: 
             - /home/bioinfo/Crabs/hcl/test_AliTV/nif.tsv 
features:
  nif:
    color: "#ff006e"
    form: arrow
    height: 30
    visible: 1
alignment:
   program: lastz
   parameter:
       - "--format=maf"
       - "--noytrim"
       - "--ambiguous=iupac"
       - "--gapped"
       - "--strand=both"
```
