### ISSUE TITLE
MSG: Failed validation of sequence '[unidentified sequence]'. Invalid characters were: _900108945113131010000441

### ISSUE THREAD

**Issue by wh960823** [AliTVTeam/AliTV-perl-interface#172]
Hi, I am trying to use AliTV to display my gene clusters, when I use the simple mode, which directly input the .fasta files, it worked. However when I use the yaml config file, it throws the error as: 'MSG: Failed validation of sequence '[unidentified sequence]'. Invalid characters were: _900108945113131010000441'. (But I have not found invalid characters in my fasta file.)
I wanna to know how this happens, and how can I solve this problem?
Thanks in advance.
Best,

-----------------
The config file
-----------------
```yaml
genomes: 
   -
    name: a
    sequence_files:
      - GCA_900108945.1.fasta
    feature_files:
      nodnif: 
             - /home/AliTV/AliTV-perl-interface/data/Rhizobia/GCA_900108945.1.txt
   - 
     name: b
     sequence_files:
      - GCA_014201025.1.fasta
     feature_files:
      nodnif: 
             - /home/AliTV/AliTV-perl-interface/data/Rhizobia/GCA_014201025.1.txt

features:
  feature1: 
    color: "#e7d3e2"
    form: arrow
    height: 30
    visible: 1
```
