### ISSUE TITLE
Allow filter criteria for feature selection

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV-perl-interface#35]
Features need to be filtered out a huge file to avoid huge amounts of manual work. Filters are defined inside the yml file and are applied while importing. Therefore different feature classes can be imported from a single gff/gb/tabular file.

**Comment by iimog** [comment]
I think this is quite nicely implemented for gff/gb files. However, it becomes tedious if you have lot's of different features. In my case I have 10 different gene classes in a gff file for three different genomes. I have to basically repeat the same section over and over again like this:
```
  - name: genome1
    sequence_files:
      - genome1.fa
    feature_files:
      Class1:
        - genome1.gff
      Class2:
        - genome1.gff
      Class3:
        - genome1.gff
      Class4:
        - genome1.gff
      Class5:
        - genome1.gff
      Class6:
        - genome1.gff
  - name: genome2
    sequence_files:
      - genome2.fa
    feature_files:
      Class1:
        - genome2.gff
      Class2:
        - genome2.gff
      Class3:
        - genome2.gff
      Class4:
        - genome2.gff
      Class5:
        - genome2.gff
      Class6:
        - genome2.gff
```
It would be nice to have an option to just provide the gff and have all features in the class given in the third column.
